### ISSUE TITLE
examples/x11rb_client: panicked at 'Encoding Error: ()'

### ISSUE THREAD

**Issue by H-M-H** [Riey/xim-rs#32]
Using fcitx-mozc and inputting anything (at least everything I have tried so far), results in a panic after pressing enter to end input composition:
```console
$ RUST_BACKTRACE=full ./target/debug/examples/x11rb_client
thread 'main' panicked at 'Encoding Error: ()', /home/hmh/git/xim-rs/src/client.rs:144:65
stack backtrace:
   0:     0x55b8cbe56510 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b8cbe56510 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b8cbe56510 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b8cbe56510 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b8cbe715ac - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55b8cbe53375 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55b8cbe5842b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b8cbe5842b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b8cbe5842b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55b8cbe57f01 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55b8cbe58af4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55b8cbe585d7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x55b8cbe56a0c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b8cbe58539 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55b8cbb92781 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55b8cbb92813 - core::result::unwrap_failed::h6160d2b4bfbb0e87
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
  16:     0x55b8cbbbfe3b - core::result::Result<T,E>::expect::h8bf6301fdd5bb5dd
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:997:23
  17:     0x55b8cbbb8233 - xim::client::handle_request::h1cd271bf3e15ac19
                               at /home/hmh/git/xim-rs/src/client.rs:144:21
  18:     0x55b8cbbd0670 - xim::x11rb::X11rbClient<C>::handle_xim_protocol::h159ede3015bc2526
                               at /home/hmh/git/xim-rs/src/x11rb.rs:579:13
  19:     0x55b8cbbd03dd - xim::x11rb::X11rbClient<C>::filter_event::hd1385622f8548adc
                               at /home/hmh/git/xim-rs/src/x11rb.rs:552:21
  20:     0x55b8cbb958f7 - x11rb_client::main::hd771181c1dedd815
                               at /home/hmh/git/xim-rs/examples/x11rb_client.rs:46:12
  21:     0x55b8cbba1bab - core::ops::function::FnOnce::call_once::h66dc34a5f8fc36b6
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  22:     0x55b8cbbb088e - std::sys_common::backtrace::__rust_begin_short_backtrace::h34d57a1ad444cbe1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x55b8cbb97191 - std::rt::lang_start::{{closure}}::hcc2ff35453349aab
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
  24:     0x55b8cbe58ff9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  25:     0x55b8cbe58ff9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  26:     0x55b8cbe58ff9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  27:     0x55b8cbe58ff9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  28:     0x55b8cbe58ff9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  29:     0x55b8cbb97170 - std::rt::lang_start::hf8f7c577c9fb03ab
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
  30:     0x55b8cbb960dc - main
  31:     0x7fc570578b25 - __libc_start_main
  32:     0x55b8cbb92f1e - _start
  33:                0x0 - <unknown>
```
examples/xlib_client crashes at the same line.

I am running KDE Plasma on Arch Linux in case that's relevant somehow.

**Comment by Riey** [comment]
It seems encoding issue can show log on develop branch with `XIM_RS_LOG=TRACE`?

**Comment by H-M-H** [comment]
On the develop branch I get:

```console
$ XIM_RS_LOG=TRACE ./target/debug/examples/x11rb_client
 INFO  xim::x11rb > Try connect fcitx
 INFO  x11rb_client > Start event loop
 INFO  xim::x11rb   > XConnected server on 113247297, transport version: 0.0, TRANSPORT_MAX: 20
 TRACE xim::x11rb   > ->: Connect { endian: Native, client_major_protocol_version: 1, client_minor_protocol_version: 0, client_auth_protocol_names: [] }
 TRACE xim::client  > <-: ConnectReply { server_major_protocol_version: 1, server_minor_protocol_version: 0 }
 TRACE x11rb_client::handler > Connected
 TRACE xim::x11rb            > ->: Open { locale: "en_US" }
 TRACE xim::client           > <-: OpenReply { input_method_id: 846, im_attrs: [Attr { id: 1, ty: Style, name: QueryInputStyle }], ic_attrs: [Attr { id: 2, ty: Long, name: InputStyle }, Attr { id: 3, ty: Window, name: ClientWindow }, Attr { id: 4, ty: Window, name: FocusWindow }, Attr { id: 5, ty: Long, name: FilterEvents }, Attr { id: 6, ty: NestedList, name: PreeditAttributes }, Attr { id: 7, ty: NestedList, name: StatusAttributes }, Attr { id: 8, ty: XFontSet, name: FontSet }, Attr { id: 9, ty: XRectangle, name: Area }, Attr { id: 10, ty: XRectangle, name: AreaNeeded }, Attr { id: 11, ty: Long, name: ColorMap }, Attr { id: 12, ty: Long, name: StdColorMap }, Attr { id: 13, ty: Long, name: Foreground }, Attr { id: 14, ty: Long, name: Background }, Attr { id: 15, ty: Long, name: BackgroundPixmap }, Attr { id: 16, ty: XPoint, name: SpotLocation }, Attr { id: 17, ty: Long, name: LineSpace }, Attr { id: 18, ty: Long, name: PreeditState }, Attr { id: 19, ty: Separator, name: SeparatorofNestedList }] }
 DEBUG xim::client           > im_attrs: [
    Attr {
        id: 1,
        ty: Style,
        name: QueryInputStyle,
    },
]
 DEBUG xim::client           > ic_attrs: [
    Attr {
        id: 2,
        ty: Long,
        name: InputStyle,
    },
    Attr {
        id: 3,
        ty: Window,
        name: ClientWindow,
    },
    Attr {
        id: 4,
        ty: Window,
        name: FocusWindow,
    },
    Attr {
        id: 5,
        ty: Long,
        name: FilterEvents,
    },
    Attr {
        id: 6,
        ty: NestedList,
        name: PreeditAttributes,
    },
    Attr {
        id: 7,
        ty: NestedList,
        name: StatusAttributes,
    },
    Attr {
        id: 8,
        ty: XFontSet,
        name: FontSet,
    },
    Attr {
        id: 9,
        ty: XRectangle,
        name: Area,
    },
    Attr {
        id: 10,
        ty: XRectangle,
        name: AreaNeeded,
    },
    Attr {
        id: 11,
        ty: Long,
        name: ColorMap,
    },
    Attr {
        id: 12,
        ty: Long,
        name: StdColorMap,
    },
    Attr {
        id: 13,
        ty: Long,
        name: Foreground,
    },
    Attr {
        id: 14,
        ty: Long,
        name: Background,
    },
    Attr {
        id: 15,
        ty: Long,
        name: BackgroundPixmap,
    },
    Attr {
        id: 16,
        ty: XPoint,
        name: SpotLocation,
    },
    Attr {
        id: 17,
        ty: Long,
        name: LineSpace,
    },
    Attr {
        id: 18,
        ty: Long,
        name: PreeditState,
    },
    Attr {
        id: 19,
        ty: Separator,
        name: SeparatorofNestedList,
    },
]
 TRACE xim::x11rb            > ->: EncodingNegotiation { input_method_id: 846, encodings: ["COMPOUND_TEXT"], encoding_infos: [] }
 TRACE xim::client           > <-: EncodingNegotiationReply { input_method_id: 846, category: 0, index: 0 }
 TRACE x11rb_client::handler > Opened
 TRACE xim::x11rb            > ->: GetImValues { input_method_id: 846, im_attributes: [1] }
 TRACE xim::client           > <-: GetImValuesReply { input_method_id: 846, im_attributes: [Attribute { id: 1, value: [5, 0, 0, 0, 4, 1, 0, 0, 4, 4, 0, 0, 4, 8, 0, 0, 8, 4, 0, 0, 8, 8, 0, 0] }] }
 TRACE xim::x11rb            > ->: CreateIc { input_method_id: 846, ic_attributes: [Attribute { id: 2, value: [2, 4, 0, 0] }, Attribute { id: 3, value: [0, 0, 160, 8] }, Attribute { id: 4, value: [0, 0, 160, 8] }, Attribute { id: 6, value: [16, 0, 4, 0, 0, 0, 0, 0] }] }
 TRACE xim::client           > <-: CreateIcReply { input_method_id: 846, input_context_id: 34 }
 INFO  x11rb_client::handler > IC created 846, 34
 TRACE xim::client           > <-: SetEventMask { input_method_id: 846, input_context_id: 34, forward_event_mask: 3, synchronous_event_mask: 4294967292 }
 INFO  x11rb_client::handler > Set event mask 846, 34, 3, 4294967292
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 36, sequence: 27, time: 43655836, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 27, xev: XEvent { response_type: 3, detail: 36, sequence: 27, time: 43655836, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 27, xev: XEvent { response_type: 3, detail: 36, sequence: 27, time: 43655836, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 37, sequence: 32, time: 43656814, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 32, xev: XEvent { response_type: 2, detail: 37, sequence: 32, time: 43656814, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 32, xev: XEvent { response_type: 2, detail: 37, sequence: 32, time: 43656814, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 65, sequence: 37, time: 43656964, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 37, xev: XEvent { response_type: 2, detail: 65, sequence: 37, time: 43656964, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true } }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 65, sequence: 40, time: 43657085, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 40, xev: XEvent { response_type: 3, detail: 65, sequence: 40, time: 43657085, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true } }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 37, sequence: 43, time: 43657154, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 43, xev: XEvent { response_type: 3, detail: 37, sequence: 43, time: 43657154, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 4, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 43, xev: XEvent { response_type: 3, detail: 37, sequence: 43, time: 43657154, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 4, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 28, sequence: 48, time: 43657614, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 48, xev: XEvent { response_type: 2, detail: 28, sequence: 48, time: 43657614, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: PreeditStart { input_method_id: 846, input_context_id: 34 }
 WARN  xim::client           > Unknown request PreeditStart { input_method_id: 846, input_context_id: 34 }
 TRACE xim::client           > <-: PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 1, chg_first: 0, chg_length: 0, status: (empty), preedit_string: [27, 36, 40, 66, 35, 116], feedbacks: [Underline] }
 WARN  xim::client           > Unknown request PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 1, chg_first: 0, chg_length: 0, status: (empty), preedit_string: [27, 36, 40, 66, 35, 116], feedbacks: [Underline] }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 32, sequence: 52, time: 43657678, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 52, xev: XEvent { response_type: 2, detail: 32, sequence: 52, time: 43657678, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 1, chg_first: 0, chg_length: 1, status: (empty), preedit_string: [27, 36, 40, 66, 36, 72], feedbacks: [Underline] }
 WARN  xim::client           > Unknown request PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 1, chg_first: 0, chg_length: 1, status: (empty), preedit_string: [27, 36, 40, 66, 36, 72], feedbacks: [Underline] }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 28, sequence: 56, time: 43657725, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 56, xev: XEvent { response_type: 3, detail: 28, sequence: 56, time: 43657725, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 56, xev: XEvent { response_type: 3, detail: 28, sequence: 56, time: 43657725, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 32, sequence: 61, time: 43657813, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 61, xev: XEvent { response_type: 3, detail: 32, sequence: 61, time: 43657813, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 61, xev: XEvent { response_type: 3, detail: 32, sequence: 61, time: 43657813, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 30, sequence: 66, time: 43657954, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 66, xev: XEvent { response_type: 2, detail: 30, sequence: 66, time: 43657954, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 2, chg_first: 0, chg_length: 1, status: (empty), preedit_string: [27, 36, 40, 66, 36, 72, 36, 38], feedbacks: [Underline, Underline] }
 WARN  xim::client           > Unknown request PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 2, chg_first: 0, chg_length: 1, status: (empty), preedit_string: [27, 36, 40, 66, 36, 72, 36, 38], feedbacks: [Underline, Underline] }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 30, sequence: 70, time: 43658032, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 70, xev: XEvent { response_type: 3, detail: 30, sequence: 70, time: 43658032, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 70, xev: XEvent { response_type: 3, detail: 30, sequence: 70, time: 43658032, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 23, sequence: 75, time: 43658312, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 75, xev: XEvent { response_type: 2, detail: 23, sequence: 75, time: 43658312, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 0, chg_first: 0, chg_length: 2, status: (empty), preedit_string: [27, 36, 40, 66, 69, 108, 53, 126], feedbacks: [Reverse, Reverse] }
 WARN  xim::client           > Unknown request PreeditDraw { input_method_id: 846, input_context_id: 34, caret: 0, chg_first: 0, chg_length: 2, status: (empty), preedit_string: [27, 36, 40, 66, 69, 108, 53, 126], feedbacks: [Reverse, Reverse] }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 3, detail: 23, sequence: 79, time: 43658422, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 79, xev: XEvent { response_type: 3, detail: 23, sequence: 79, time: 43658422, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: SYNCHRONOUS, serial_number: 79, xev: XEvent { response_type: 3, detail: 23, sequence: 79, time: 43658422, root: 1944, event: 144703488, child: 0, root_x: 0, root_y: 0, event_x: 1387, event_y: 610, state: 0, same_screen: false } }
 TRACE xim::x11rb            > ->: SyncReply { input_method_id: 846, input_context_id: 34 }
 TRACE x11rb_client          > Send: KeyPressEvent { response_type: 2, detail: 36, sequence: 84, time: 43658727, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true }
 TRACE xim::x11rb            > ->: ForwardEvent { input_method_id: 846, input_context_id: 34, flag: (empty), serial_number: 84, xev: XEvent { response_type: 2, detail: 36, sequence: 84, time: 43658727, root: 1944, event: 144703488, child: 0, root_x: 1387, root_y: 634, event_x: 1387, event_y: 610, state: 0, same_screen: true } }
 TRACE xim::client           > <-: Commit { input_method_id: 846, input_context_id: 34, data: Chars { commited: [27, 36, 40, 66, 69, 108, 53, 126], syncronous: false } }
thread 'main' panicked at 'Encoding Error: [27, 36, 40, 66, 69, 108, 53, 126]', /home/hmh/git/xim-rs/src/client.rs:148:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Riey** [comment]
@H-M-H Thanks, now I'm sure fcitx-mozc send string which xim-rs is not support yet

Did you know what's original string? I'll try to decode

**Comment by H-M-H** [comment]
I just typed 東京.

**Comment by Riey** [comment]
Can you try latest develop? I don't know it works other characters

**Comment by H-M-H** [comment]
Nice, it's working now, thanks!

**Comment by Riey** [comment]
Please check other inputs then close this when they work well :D

**Comment by H-M-H** [comment]
So far everything is working.
